#####################
# Defines the Schemas for routes
# https://json-schema.org/learn/miscellaneous-examples.html
#####################
labels:
  ok:  "resp.status == 200"
  err: "resp.status != 200"

verify:
  in: true
  out: true

routes:

  /entity/*:
    put:
      in: EntityProperties.json
      ok: Urn.json
      err: Generic.json
    
    post:
      in: EntityUpdate.json
      ok: Urn.json
      err: Generic.json 
    
    get:
      ok: Entity.json
      err: Generic.json
  
  /relate/*:
    post: 
      in: Relation.json
      ok: Generic.json
      err: Generic.json

  /unrelate/*:
    post: 
      in: Relation.json
      ok: Generic.json
      err: Generic.json

  /version/*:
    get:
      ok: Urn.json
      err: Generic.json

  /versions/*:
    get:
      params: PageParams.json
      ok: Entity.json
      err: Generic.json
