#####################
# Defines the Schemas for routes
# https://json-schema.org/learn/miscellaneous-examples.html
#####################
labels:
  ok:  "resp.status == 200"
  err: "resp.status != 200"

verify:
  in: true
  out: true

routes:

  /event:
    put:
      in: Event.json
      ok: Generic.json
      err: Generic.json
